### ISSUE TITLE
Is this plugin still maintained

### ISSUE THREAD

**Issue by ryssbowh** [la-haute-societe/craft-restrict-asset-delete#11]
Hi,

It seems a couple of issues and PR have not been addressed in the past 6 months, so I'm wondering if this plugin is still maintained.

As a plugin developer myself I'd be happy to take over management if that something you'd consider, this plugin is very useful and I'm considering re-making it if this plugin is considered as abandonned, especially with the released of Craft 4 less and less people will use it if there's no version released for it.

Thank you

**Comment by adrienne** [comment]
@ryssbowh - it's MIT licensed so if you don't hear from @lhs-dev you could just fork it with a different name, i'm thinking? (I, too, would like a Craft 4 version)

**Comment by ryssbowh** [comment]
@adrienne good idea, would leave a bit of time for @lhs-dev to comment on this before remaking a new plugin

**Comment by lhs-dev** [comment]
Hi, sorry we are busy.
We will check internally if we will update this plugin.
We will come back to you in few weeks.
Sorry for the delay.

**Comment by ryssbowh** [comment]
@adrienne I've taken the idea of this plugin further to restrict deletions of all elements, it's also Craft 4 ready : https://github.com/ryssbowh/craft-restrict-deletions

**Comment by nstcactus** [comment]
Yes, this plugin is still maintained, but on a "best-effort basis".
