### ISSUE TITLE
Restriction not working anymore

### ISSUE THREAD

**Issue by ryssbowh** [la-haute-societe/craft-restrict-asset-delete#6]
Hi,

I've noticed the restriction stopped working recently, I don't know if it's because of a change in this plugin or my update to Craft 3.7.
I use it with Craft 3.7 Solo as an admin with the setting `adminCanSkipRestriction` off, so unless you have changed your logic I should be prevented to delete used assets but I'm not.

I think the issue is in the `canSkipRestriction`, it always returns true for an admin :
```
protected function canSkipRestriction()
    {
        $user = Craft::$app->user;
        return (
                $user->getIsAdmin()                                   //true
                && $this->getSettings()->adminCanSkipRestriction      //false
            )
            || $user->checkPermission('restrict-asset-delete:skip-restriction');  //always true because I'm an admin
    }
```
The following fixes it :
```
protected function canSkipRestriction()
    {
        $user = Craft::$app->user;
        return $user->getIsAdmin() ? $this->getSettings()->adminCanSkipRestriction : $user->checkPermission('restrict-asset-delete:skip-restriction');
    }
```
I haven't tried with a permission driven user on a Pro edition though. I can look at a PR in the next couple of days

**Comment by nstcactus** [comment]
Closed by 423922469f9ba3c8b548c97a95831bfa2dcd8519.
Version 1.2.0 is out with that change.
