### ISSUE TITLE
Don't look at revisions for used assets

### ISSUE THREAD

**Issue by ryssbowh** [la-haute-societe/craft-restrict-asset-delete#7]
Hi,

I'm using this plugin on a lot of websites for clients. On some with a lot of contents (therefore a lot of revisions), the restriction does its job a bit too well and prevents assets used in any revision to be deleted.
That is a bit of a problem as you then search for the entry that references that asset but you can't find it if it's a revision, and in most cases you don't really care about revisions loosing a reference to an asset.

Would it make sense to you to only look at the used active entries ?
It could come as an option to bypass revisions (and maybe inactive entries) ?

Thank you

**Comment by nstcactus** [comment]
Closed by 785d70031093c49fc6e9568532b3b1084145b526.
Version 1.2.0 is out with that change.
